### ISSUE TITLE
expose correct list of variables in climate_widget_graph.js

### ISSUE THREAD

**Issue by embeepea** [nemac/climate-widget-graph#1]
The "variables" and "ms_variables" lists at the top of climate_widget_graph.js contain several unused variables that should be removed.  Also, these two lists should be combined into one normalized list.  Note that code will need to be changed accordingly when this happens.

**Comment by cmy2k** [comment]
What is in the current variable list is consistent with what has been processed and what is in the inventory sheet that we have committed to delivering.
