### ISSUE TITLE
set reasonable pan/zoom limits

### ISSUE THREAD

**Issue by embeepea** [nemac/climate-widget-graph#6]
probably disallow horiz pan and zoom both for monthly, seasonal plots

**Comment by cmy2k** [comment]
Initial pass at this done in this commit:

https://github.com/nemac/climate-widget-graph/commit/e0f491cb37669052896fd14be9ae1a23f7ad237a

Can be improved.

**Comment by cmy2k** [comment]
Improved by this

https://github.com/nemac/climate-widget-graph/commit/1c8764dd8a1aca53d4fd17f9ede0dc2e5abf1486

Done for now.
